### ISSUE TITLE
Maintaining Customer Object Through Forms

### ISSUE THREAD

**Issue by d-dtm** [tha7556/PC-Hawk-Customs#5]
How do we go about keeping one customer 'alive' throughout the forms, since each form requires a reload? Thoughts?

**Comment by tha7556** [comment]
We could have each closed form pass the customer object to the newly opened form

**Comment by d-dtm** [comment]
Other Ideas:

- Form Master Class, keeps track of forms and User

- User Boolean, tracks login status
